In [2]:
import pandas as pd
print(pd.__version__)

3.0.3

Application of Pandas
- Easy to handle
- Size mutable
- Automatic and explicit data alignment
- Powerfull and flexiable
- Inteligent label

In [ ]:
student={
    'id':["S001","S002","S003","S004"],
    'name':["abc1","abc2","abc3","abc4"],
    'age:':[21,23,20,24]
}
df=pd.DataFrame(student)
df.shape
df.size
df.columns
df

     id  name  age:
0  S001  abc1    21
1  S002  abc2    23
2  S003  abc3    20
3  S004  abc4    24

Export DataFrame to CSV file

In [ ]:
df.to_csv("studentData.csv", index=False)

Imp0rt CSV Files

In [5]:
#Same Folder
same_df= pd.read_csv("studentData.csv")
same_df

     id  name  age:
0  S001  abc1    21
1  S002  abc2    23
2  S003  abc3    20
3  S004  abc4    24

In [6]:
#Diffrent folder
diff_df=pd.read_csv("C:/Users/ganap/Datascience/Pandas/Subdata_pandas/employee.csv")
diff_df

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/ganap/Datascience/Pandas/Subdata_pandas/employee.csv'

Import exel files

In [ ]:
#cmd: >pip install openpyxl
excel_df=pd.read_excel("Subdata_pandas/expense.xlsx")
excel_df