In [15]:
import pandas as pd
import numpy as np

### Duplicate Data

In [4]:
cdata=pd.read_csv("Subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [9]:
cdata.duplicated()

#Check emp id
cdata['EEID'].duplicated()
cdata['Name'].duplicated()

#Drop data
cdata['EEID'].drop_duplicates()

0    EMP01
1    EMP02
2    EMP03
4    EMP05
5    EMP06
Name: EEID, dtype: str

### Missing Value

In [13]:
#Find null values
cdata.isnull().sum()

EEID      0
Name      1
gender    1
salary    2
dtype: int64

In [14]:
#Element null values
cdata.dropna()

    EEID    Name gender   salary
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0

In [ ]:
cdata.replace(np.nan,"Empty Data")

    EEID        Name      gender      salary
0  EMP01      ayushi           F  Empty Data
1  EMP02       rohit           M     25000.0
2  EMP03    pranjali  Empty Data     27000.0
3  EMP01      ayushi           F     20000.0
4  EMP05  Empty Data           M     25000.0
5  EMP06       rohit           M  Empty Data
6  EMP02       rohit           M     25000.0

In [ ]:
# Replace Nan with any value
cdata['salary'].replace(np.nan, 5000)

cdata['Name']

0      ayushi
1       rohit
2    pranjali
3      ayushi
4         NaN
5       rohit
6       rohit
Name: Name, dtype: str

In [27]:
#Replace Nan with any value
mean=np.mean(cdata['salary'])
mean
#Method 1
cdata['salary'].replace(np.nan,mean)

#Method 2
cdata['salary']=cdata['salary'].fillna(mean)
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0

In [ ]:
#Forward Fill - from previous row
#cdata.ffill()

#Backward Fill - from next row
cdata.bfill()

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      F  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     rohit      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0