# Column Tranformation in Pandas

In [22]:
import pandas as pd
import numpy as np

### Row & Column Selection

In [3]:
sData=pd.read_csv('Subdata_pandas/student.csv')
sData

    id firstName  lastName  age  marks   fees
0  101    Akshay    Shetty   20     85  25000
1  102    Ananya       Rao   21     92  30000
2  103     Rohit  Bhandary   19     76  28000
3  104     Nisha   D'Souza   20     88  25000
4  105   Karthik   Poojary   22     69  32000
5  106    Shreya    Shetty   19     95  30000
6  107     Rohan      Naik   21     72  27000
7  108   Deepika      Bhat   20     81  28000
8  109  Abhishek    Kotian   22     64  26000
9  110     Pooja       Rai   19     90  30000

In [4]:
# Select a specific column
sData[['firstName','marks']]

  firstName  marks
0    Akshay     85
1    Ananya     92
2     Rohit     76
3     Nisha     88
4   Karthik     69
5    Shreya     95
6     Rohan     72
7   Deepika     81
8  Abhishek     64
9     Pooja     90

In [17]:
# based on name select row
sData.loc[sData.firstName=="Rohit"]
sData.loc[sData.id==103]
sData.info()
sData.loc[sData.marks>=90]
sData.loc[:3]
sData.iloc[:5,1:4]

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     int64
 1   firstName  10 non-null     str
 2   lastName   10 non-null     str
 3   age        10 non-null     int64
 4   marks      10 non-null     int64
 5   fees       10 non-null     int64
dtypes: int64(4), str(2)
memory usage: 726.0 bytes

  firstName  lastName  age
0    Akshay    Shetty   20
1    Ananya       Rao   21
2     Rohit  Bhandary   19
3     Nisha   D'Souza   20
4   Karthik   Poojary   22

### Filter

In [18]:
# Select student firstName, age and fees who have marks more than 90

sData[['firstName','age','fees']].loc[sData.marks>=90]

  firstName  age   fees
1    Ananya   21  30000
5    Shreya   19  30000
9     Pooja   19  30000

In [21]:
# Select student age equal, above 20
sData['age']>=20
sData[sData['age']>=20]
sData_age_filter=sData[sData['age']>=20]
sData_age_filter

    id firstName lastName  age  marks   fees
0  101    Akshay   Shetty   20     85  25000
1  102    Ananya      Rao   21     92  30000
3  104     Nisha  D'Souza   20     88  25000
4  105   Karthik  Poojary   22     69  32000
6  107     Rohan     Naik   21     72  27000
7  108   Deepika     Bhat   20     81  28000
8  109  Abhishek   Kotian   22     64  26000

In [ ]:
#Finding mean
mean=np.mean(sData['fees'])
mean

np.float64(28100.0)

In [24]:
sData.where(sData['age']>=20, other="Minor")

      id firstName lastName    age  marks   fees
0    101    Akshay   Shetty     20     85  25000
1    102    Ananya      Rao     21     92  30000
2  Minor     Minor    Minor  Minor  Minor  Minor
3    104     Nisha  D'Souza     20     88  25000
4    105   Karthik  Poojary     22     69  32000
5  Minor     Minor    Minor  Minor  Minor  Minor
6    107     Rohan     Naik     21     72  27000
7    108   Deepika     Bhat     20     81  28000
8    109  Abhishek   Kotian     22     64  26000
9  Minor     Minor    Minor  Minor  Minor  Minor

In [27]:
meanmarks=np.mean(sData['marks'])
meanmarks
sData.where(sData['marks']>=meanmarks, other="Pass")

     id firstName lastName   age marks   fees
0   101    Akshay   Shetty    20    85  25000
1   102    Ananya      Rao    21    92  30000
2  Pass      Pass     Pass  Pass  Pass   Pass
3   104     Nisha  D'Souza    20    88  25000
4  Pass      Pass     Pass  Pass  Pass   Pass
5   106    Shreya   Shetty    19    95  30000
6  Pass      Pass     Pass  Pass  Pass   Pass
7  Pass      Pass     Pass  Pass  Pass   Pass
8  Pass      Pass     Pass  Pass  Pass   Pass
9   110     Pooja      Rai    19    90  30000